/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package strike.pkg1945;

import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import static strike.pkg1945.Pause.high;

/**
 *
 * @author Widean Nagari
 */
public class Continue extends javax.swing.JFrame {

    /**
     * Creates new form Continue
     */
    static ArrayList<Player> p;
    static ArrayList<HighScores> high;
    static ArrayList<inGameData> data;
    static MainMenu m;
    public Continue(MainMenu main, ArrayList<HighScores> h, ArrayList<Player> player, ArrayList<inGameData> d) {
        initComponents();
        p = player;
        high = h;
        data = d;
        m = main;
        for (Player play : p) {
            if (play.getPosisiSave() == 0) {
                satu.setText("1. "+play.getNama());
            }else if (play.getPosisiSave() == 1) {
                dua.setText("2. "+play.getNama());
            }else if (play.getPosisiSave() == 2) {
                tiga.setText("3. "+play.getNama());
            }
        }
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        buang1 = new javax.swing.JButton();
        buang2 = new javax.swing.JButton();
        buang3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/Continue2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(760, 80, 420, 120);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/Back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 850, 200, 75);

        satu.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        satu.setText("1. Save Data Not Found!");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        jPanel1.add(satu);
        satu.setBounds(230, 260, 1300, 130);

        dua.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        dua.setText("2. Save Data Not Found!");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        jPanel1.add(dua);
        dua.setBounds(230, 440, 1300, 130);

        tiga.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tiga.setText("3. Save Data Not Found!");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        jPanel1.add(tiga);
        tiga.setBounds(230, 630, 1300, 130);

        buang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/sampah.png"))); // NOI18N
        buang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buang1ActionPerformed(evt);
            }
        });
        jPanel1.add(buang1);
        buang1.setBounds(1620, 260, 110, 130);

        buang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/sampah.png"))); // NOI18N
        buang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buang2ActionPerformed(evt);
            }
        });
        jPanel1.add(buang2);
        buang2.setBounds(1620, 440, 110, 130);

        buang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/sampah.png"))); // NOI18N
        buang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buang3ActionPerformed(evt);
            }
        });
        jPanel1.add(buang3);
        buang3.setBounds(1620, 630, 110, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/Main Menu.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 2100, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
        if (!satu.getText().equals("1. Save Data Not Found!")) {
            GameFrame frame = new GameFrame(m,high,p,data,0);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
        if (!dua.getText().equals("2. Save Data Not Found!")) {
            GameFrame frame = new GameFrame(m,high,p,data,1);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
        if (!tiga.getText().equals("3. Save Data Not Found!")) {
            GameFrame frame = new GameFrame(m,high,p,data,2);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_tigaActionPerformed

    private void buang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buang1ActionPerformed
        // TODO add your handling code here:
        if (!satu.getText().equals("1. Save Data Not Found!")) {
            if (!dua.getText().equals("2. Save Data Not Found!")) {
                dua.setText("2. Save Data Not Found!");m.p.remove(0);m.data.remove(0);
                m.p.get(0).setPosisiSave(0);
                if (!tiga.getText().equals("3. Save Data Not Found!")) {
                    tiga.setText("3. Save Data Not Found!");m.p.get(1).setPosisiSave(1);
                }
            }else{
                satu.setText("1. Save Data Not Found!");m.p.remove(0);m.data.remove(0);
            }
            for (Player play : m.p) {
                if (play.getPosisiSave() == 0) {
                    satu.setText("1. "+play.getNama());
                }else if (play.getPosisiSave() == 1) {
                    dua.setText("2. "+play.getNama());
                }else if (play.getPosisiSave() == 2) {
                    tiga.setText("3. "+play.getNama());
                }
            }
        }
        try{
            FileOutputStream fo = new FileOutputStream("Player.txt");
            ObjectOutputStream out = new ObjectOutputStream(fo);
            out.writeObject(m.p);
            out.close();
            fo.close();
        }catch(IOException ex){
            ex.printStackTrace();
        } 
        
        try{
            FileOutputStream fo = new FileOutputStream("Data.txt");
            ObjectOutputStream out = new ObjectOutputStream(fo);
            out.writeObject(m.data);
            out.close();
            fo.close();
        }catch(IOException ex){
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_buang1ActionPerformed

    private void buang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buang2ActionPerformed
        // TODO add your handling code here:
        if (!dua.getText().equals("2. Save Data Not Found!")) {
            if(!tiga.getText().equals("3. Save Data Not Found!")){
                tiga.setText("3. Save Data Not Found!");m.p.remove(1);m.data.remove(1);
                m.p.get(1).setPosisiSave(1);
            }else{dua.setText("2. Save Data Not Found!");m.p.remove(1);m.data.remove(1);}
            for (Player play : m.p) {
                if (play.getPosisiSave() == 0) {
                    satu.setText("1. "+play.getNama());
                }else if (play.getPosisiSave() == 1) {
                    dua.setText("2. "+play.getNama());
                }else if (play.getPosisiSave() == 2) {
                    tiga.setText("3. "+play.getNama());
                }
            }
        }
        try{
            FileOutputStream fo = new FileOutputStream("Player.txt");
            ObjectOutputStream out = new ObjectOutputStream(fo);
            out.writeObject(m.p);
            out.close();
            fo.close();
        }catch(IOException ex){
            ex.printStackTrace();
        } 
        
        try{
            FileOutputStream fo = new FileOutputStream("Data.txt");
            ObjectOutputStream out = new ObjectOutputStream(fo);
            out.writeObject(m.data);
            out.close();
            fo.close();
        }catch(IOException ex){
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_buang2ActionPerformed

    private void buang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buang3ActionPerformed
        // TODO add your handling code here:
        if (!tiga.getText().equals("3. Save Data Not Found!")) {
            tiga.setText("3. Save Data Not Found!");
            m.p.remove(2);
            m.data.remove(2);
            for (Player play : m.p) {
                if (play.getPosisiSave() == 0) {
                    satu.setText("1. "+play.getNama());
                }else if (play.getPosisiSave() == 1) {
                    dua.setText("2. "+play.getNama());
                }else if (play.getPosisiSave() == 2) {
                    tiga.setText("3. "+play.getNama());
                }
            }
            try{
                FileOutputStream fo = new FileOutputStream("Player.txt");
                ObjectOutputStream out = new ObjectOutputStream(fo);
                out.writeObject(m.p);
                out.close();
                fo.close();
            }catch(IOException ex){
                ex.printStackTrace();
            } 

            try{
                FileOutputStream fo = new FileOutputStream("Data.txt");
                ObjectOutputStream out = new ObjectOutputStream(fo);
                out.writeObject(m.data);
                out.close();
                fo.close();
            }catch(IOException ex){
                ex.printStackTrace();
            } 
        }
    }//GEN-LAST:event_buang3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Continue(m,high,p,data).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buang1;
    private javax.swing.JButton buang2;
    private javax.swing.JButton buang3;
    private javax.swing.JButton dua;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton satu;
    private javax.swing.JButton tiga;
    // End of variables declaration//GEN-END:variables
}
