/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package strike.pkg1945;

import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Widean Nagari
 */
public class Status extends javax.swing.JFrame {

    /**
     * Creates new form Status
     */
    public Status() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        defend = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        hp = new javax.swing.JLabel();
        gold = new javax.swing.JLabel();
        bullet = new javax.swing.JLabel();
        skor = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        attack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/Status.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(830, 80, 300, 120);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/Back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 800, 200, 75);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("HP :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(930, 370, 80, 60);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Spaceship Type :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(700, 630, 310, 60);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(880, 240, 140, 60);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Number of Bullet :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(670, 700, 340, 60);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Gold :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(900, 430, 110, 60);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Defend :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(850, 570, 160, 60);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Attack :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(860, 500, 150, 60);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Score :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(880, 300, 140, 60);

        defend.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        defend.setForeground(new java.awt.Color(240, 240, 240));
        defend.setText("10");
        jPanel1.add(defend);
        defend.setBounds(1030, 570, 560, 60);

        nama.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        nama.setForeground(new java.awt.Color(240, 240, 240));
        nama.setText("x");
        jPanel1.add(nama);
        nama.setBounds(1030, 240, 740, 60);

        hp.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        hp.setForeground(new java.awt.Color(240, 240, 240));
        hp.setText("1500/1500");
        jPanel1.add(hp);
        hp.setBounds(1030, 370, 480, 60);

        gold.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        gold.setForeground(new java.awt.Color(240, 240, 240));
        gold.setText("0");
        jPanel1.add(gold);
        gold.setBounds(1030, 440, 510, 40);

        bullet.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        bullet.setForeground(new java.awt.Color(240, 240, 240));
        bullet.setText("1");
        jPanel1.add(bullet);
        bullet.setBounds(1030, 700, 450, 60);

        skor.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        skor.setForeground(new java.awt.Color(240, 240, 240));
        skor.setText("0");
        jPanel1.add(skor);
        skor.setBounds(1030, 310, 500, 40);

        type.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        type.setForeground(new java.awt.Color(240, 240, 240));
        type.setText("x");
        jPanel1.add(type);
        type.setBounds(1030, 630, 670, 60);

        attack.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        attack.setForeground(new java.awt.Color(240, 240, 240));
        attack.setText("50");
        jPanel1.add(attack);
        attack.setBounds(1030, 500, 530, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strike/pkg1945/Gambar/menu.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attack;
    private javax.swing.JLabel bullet;
    private javax.swing.JLabel defend;
    private javax.swing.JLabel gold;
    private javax.swing.JLabel hp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel skor;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
